# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0002_auto_20161104_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='discuss.Question'),
        ),
    ]
